name: base
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - ipywidgets=7.5.1
  - jupyter_contrib_nbextensions
  - numpy
  - ipympl
  - voila
  - ipyevents